### ISSUE TITLE
Fix Labor history ordering

### ISSUE THREAD

**Issue by sheggen** [BCStudentSoftwareDevTeam/lsf#344]
Labor history is supposed to show LSFs in the reverse order (i.e., the most future term at the top). Summer and Fall are sorted incorrectly. Others may be as well. 

Related: Fall as a term will not be used in the future. Academic Year (AY) should be used moving forward. This may no longer be an issue once that code is in place.

<img width="660" alt="Screen Shot 2022-08-09 at 11 14 27 AM" src="https://user-images.githubusercontent.com/1906220/183688939-9d312d74-5ac2-4861-b89e-42348ca6b760.png">

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Order of forms in Labor History #344](https://trello.com/c/GMxXiT1K/474-order-of-forms-in-labor-history-344)
