### ISSUE TITLE
Department dropdown is unsearchable

### ISSUE THREAD

**Issue by sheggen** [BCStudentSoftwareDevTeam/lsf#345]
In the supervisor portal, under "Department Students", there is a dropdown for the department. The only way to select a department is to scroll through the very long list and find the one you want. 

Instead, implement the bootstrap Search feature, so users can type in the department they want and it filters. 

<img width="640" alt="Screen Shot 2022-08-09 at 11 18 32 AM" src="https://user-images.githubusercontent.com/1906220/183689491-c6c3dbf5-563c-4f45-84fc-63a245d71f5b.png">

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Department dropdown is unsearchable #345](https://trello.com/c/1ka8AYm3/475-department-dropdown-is-unsearchable-345)

**Comment by bledsoef** [comment]
We are taking care of this in another issue.
