### ISSUE TITLE
Withdraw button in labor history for overloads

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/lsf#354]
New overloads should have a Withdraw button in the modal from Labor History. Students and admins should both be able to withdraw.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Withdraw button in labor history for overloads #354](https://trello.com/c/b1TRLnvg/480-withdraw-button-in-labor-history-for-overloads-354)
