### ISSUE TITLE
Update user names from Tracy on a regular interval

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/lsf#357]
We need a script that will select all students and supervisors from the Tracy database and update our Student and Supervisor records so that the names match. For most of this work we can use existing functions. The script will be called by cron to run nightly.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update user names from Tracy on a regular interval #357](https://trello.com/c/4Th5JfTF/482-update-user-names-from-tracy-on-a-regular-interval-357)
