### ISSUE TITLE
Rework Supervisor Portal

### ISSUE THREAD

**Issue by bledsoef** [BCStudentSoftwareDevTeam/lsf#362]
User Story: As a Supervisor, I want to view and manage department labor students efficiently, so that I can maintain labor student records effectively. 

Acceptance Criteria: 

 - Should be able to easily differentiate labor students by the term they were hired in.
 - Should only have one page to manage all Labor students in my department. 

Note:
 - Admins should still be able to access all departments from the drop-down.

Sub-issue of #359

**Comment by bledsoef** [comment]
We are converting Form Search to the new supervisor portal so we are getting rid of the existing supervisor portal. 
- For each result on Form Search, have a direct link to Labor History
- Make the Form Search an accordion so after searching it is collapsible and you can go right to the table.
- Rename to supervisor portal

**Comment by tylerpar99** [comment]
Merged.
