### ISSUE TITLE
Faculty and staff should be able to search their departments form's and students

### ISSUE THREAD

**Issue by bledsoef** [BCStudentSoftwareDevTeam/lsf#366]
User Story: As a supervisor, I should be able to search forms and students, so that I can easily access the records or forms I need. 

Acceptance Criteria: 
- A supervisor should be able to access the form search and student search that Admins currently have access to.
- If they are a supervisor they should have access limited to the students in their department.
- Admin permissions should remain the same.

Sub-issue of #359

**Comment by tylerpar99** [comment]
Merged.
