### ISSUE TITLE
Update student classification from Tracy

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/lsf#371]
We need to update the student name updater to update more fields from Tracy, like student classification.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update student classification from Tracy #371](https://trello.com/c/PziTWb9Y/551-update-student-classification-from-tracy-371)

**Comment by BrianRamsay** [comment]
We need a script that will select all students and supervisors from the Tracy database and update our Student and Supervisor records. For most of this work we can use existing functions. The script will be called by cron to run nightly.

**Comment by tylerpar99** [comment]
Notes: 
We want to grab our users and for each user call an update function that will take Tracy's data for every field (Excepts IDs) and update them in our DB. Celts has an updateusers.py file that we can take a look at and there is already an existing update user from the Tracy function in LSF.
