### ISSUE TITLE
Add a link to the student overload reason page for admins

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/lsf#374]
Currently only students can get to the student overload reason page. Admins should have a link to the page and be able to use it so they can help students.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a link to the student overload reason page for admins #374](https://trello.com/c/2fpbGOou/554-add-a-link-to-the-student-overload-reason-page-for-admins-374)

**Comment by BrianRamsay** [comment]
Completed
