### ISSUE TITLE
Supervisors should be able to evaluate after term ends

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/lsf#375]
There is no evaluation option for supervisors after a term ends (reportedly). The evaluation option should be there as long as evaluation is open for a term.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Supervisors should be able to evaluate after term ends #375](https://trello.com/c/U9ipamul/555-supervisors-should-be-able-to-evaluate-after-term-ends-375)

**Comment by tylerpar99** [comment]
Tried to recreate the issue. Closed the term and set the dates to one date prior to the date of testing, left the final evaluation option open, and was still able to see the evaluate button and access the evaluate UI. Will need confirmation that this is no longer an issue. @BrianRamsay @Andersonstettner

**Comment by solijonovam** [comment]
no longer an issue
