### ISSUE TITLE
Form Search breaks searching for a student

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/lsf#377]
Searching for only David Hagan in the form search results in an ajax error.

**Comment by Andersonstettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Form Search download doesn't match table #376](https://trello.com/c/F1QzCi1r/556-form-search-download-doesnt-match-table-376)

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Form Search breaks searching for a student #377](https://trello.com/c/9M0YAW7b/557-form-search-breaks-searching-for-a-student-377)

**Comment by tylerpar99** [comment]
The issue does not reoccur when using the updated UI. Assuming this might have unintentionally been fixed with the rework. Will need confirmation of this though. @BrianRamsay @Andersonstettner
