### ISSUE TITLE
Term start and end date are blank in Term Management

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/lsf#379]
The start and end dates can be set in Term Management but show up as blank when the page is revisited.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Term start and end date are blank in Term Management #379](https://trello.com/c/b7FCO3wI/559-term-start-and-end-date-are-blank-in-term-management-379)
