### ISSUE TITLE
Fix pending form adjustment for adjusting supervisors or hours

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/lsf#393]
If a user tires to change a supervisor or hours on a pending form they get a success message on the form but the database never updates so the change never goes thought.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix pending form adjustment for adjusting supervisors or hours #393](https://trello.com/c/pZcTvalU/577-fix-pending-form-adjustment-for-adjusting-supervisors-or-hours-393)

**Comment by sreynit02** [comment]
This is no longer a bug. The Labor Status Form only get updated when the adjustment form has been approved.
