### ISSUE TITLE
Imported Courses and new courses with the same course name can't have different sections

### ISSUE THREAD

**Issue by sheggen** [BCStudentSoftwareDevTeam/lsf#408]
1. Import a course using the +Schedule a Course >> Import Courses feature
2. Add a new course using the +Schedule a Course button, with the same course name as 1.
3. First, it will give an error about section number in red (I missed the exact language). But, it will also give it the same section A as the imported course, and it will not record the "Last Edited" field. Something is breaking on the back-end
4. You can't edit either course to give it Section B.

**Comment by solijonovam** [comment]
is this for LSF?

**Comment by sheggen** [comment]
No. This is for CAS 🤣
