### ISSUE TITLE
button isn't blocked enough

### ISSUE THREAD

**Issue by solijonovam** [BCStudentSoftwareDevTeam/lsf#410]
![image](https://user-images.githubusercontent.com/97661971/232881265-61cd455b-6689-4987-bb74-406dfd1cb66d.png)

summary:
currently, a user can remove the disabled attribute in dev. tools in term management to open a term. this is a security concern.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [button isn't blocked enough #410](https://trello.com/c/b7wUwUW0/608-button-isnt-blocked-enough-410)
