### ISSUE TITLE
Refactor Supervisor Portal UI

### ISSUE THREAD

**Issue by bledsoef** [BCStudentSoftwareDevTeam/lsf#440]
## Issue
There are a number of UI decisions or visual bugs that don't make a lot of sense in the current Supervisor Portal

## Needs Changing
- The search and clear buttons are visually outside of accordion, even though they technically are part of it.
![Screenshot from 2024-09-05 16-21-10](https://github.com/user-attachments/assets/3d67fdc5-fe90-425f-aa5b-c4e903294022)

- Figure out better location for download button. It is currently in a weird location.
![Screenshot from 2024-09-05 16-24-05](https://github.com/user-attachments/assets/7f38c31a-d91a-4ec1-93a9-75862569f1de)

- One of the Limit Form Type options is "overload". That is not exactly intuitive for supervisors.
![Screenshot from 2024-09-05 16-26-04](https://github.com/user-attachments/assets/ec009f1d-ee8a-45bf-87ee-781ccafe7049)

- It would be convenient to be able to see the B number on the results table without having to click on the student's name.

- If we choose to not completely refactor the table, it would be helpful to potentially rearrange the table because the Student is likely the most important column, but it can be hard to find.

**Comment by WackyWeaver** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor Supervisor Portal UI](https://trello.com/c/rbVkyiq8/822-refactor-supervisor-portal-ui)
