### ISSUE TITLE
Errors and Unwanted Form Search Behavior

### ISSUE THREAD

**Issue by WackyWeaver** [BCStudentSoftwareDevTeam/lsf#443]
## Problem
- Weird or wonky behavior or errors with the form search 

## Changes to make 
- Error when sorting by supervisor
- Add pre-student approval forms pending forms preset
- Remove missing evaluation preset and options
- Prevent download from breaking when the table is empty by adding check.

**Comment by bledsoef** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Errors and Unwanted Form Search Behavior](https://trello.com/c/WcxsuYlP/818-errors-and-unwanted-form-search-behavior)
